<?php

/**
 * Implements hook_theme() to provide a theme for CatsEntityListBuilder.
 */
function cats_module_theme($existing, $type, $theme, $path) {
  return [
    'cats_entity_list_builder' => [
      'variables' => [
        'rows' => [],
        'header' => [],
        'attributes' => [],
      ],
      'template' => 'CatsEntityListBuilder',
      '#attached' => [
        'library' => ['core/drupal.dialog.ajax'],
      ],
    ],
    'cats_module_list_form' => [
      'render element' => 'form'
    ],
  ];
}
function cats_module_preprocess_cats_entity_list_builder(&$variables) {
  $variables['#attached']['library'][] = 'cats_module/cats_module_js';
}
